dynamicBatch:
  enable: False
  maxBatchSize: 12
  idleBatchSize: 5
  maxBatchInterval: 0.002
env:
  python: 3.8.10
  pip: 21.1.3
  cpu:
    instance: Standard_F16s_v2
    worker_count: 6
    thread_count: 1
  gpu:
    instance: Standard_NC6s_v3
    worker_count: 1
    thread_count: 24